# Repo: clawdbot/clawdbot (fork into your own account first)
# Purpose: Build the Android debug APK from apps/android and upload it as a GitHub Actions artifact.

name: Android (Node) - Build Debug APK

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug APK
        working-directory: apps/android
        run: |
          chmod +x ./gradlew
          ./gradlew :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: clawdbot-node-android-debug-apk
          path: apps/android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
